# Generated by Django 3.2.6 on 2021-12-20 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 12, 50, 19, 31374, tzinfo=utc)),
        ),
    ]
