# Generated by Django 3.2.6 on 2021-12-20 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 15, 1, 47, 210475, tzinfo=utc)),
        ),
    ]
