# Generated by Django 3.2.6 on 2022-06-08 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220608_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 11, 3, 24, 20903, tzinfo=utc)),
        ),
    ]
