# Generated by Django 3.2.6 on 2022-06-08 11:05

import catalog.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 11, 5, 11, 957122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True, validators=[catalog.validators.validar_gt_0, catalog.validators.validar_lt_10]),
        ),
    ]
