# Generated by Django 3.2.6 on 2022-06-08 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220608_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 11, 5, 53, 558386, tzinfo=utc)),
        ),
    ]
